"""
游戏配置文件
包含所有的游戏常量和配置参数
"""

# 屏幕配置
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# 蛇的配置
SNAKE_COLOR = (0, 0, 255)  # 红色蛇身
HEAD_COLOR = (200, 0, 200)  # 紫色蛇头
SNAKE_THICKNESS = 20
HEAD_RADIUS = 20
INITIAL_LENGTH = 150  # 初始长度
LENGTH_INCREASE = 50  # 每次吃食物增加的长度

# 食物配置
FOOD_MARGIN = 100  # 食物与边缘的距离
FOOD_IMAGE = "apple.png"

# 碰撞检测配置
COLLISION_THRESHOLD = 15  # 碰撞检测阈值（像素）
COLLISION_CHECK_INTERVAL = 5  # 每5帧检查一次自碰撞

# 性能配置
TARGET_FPS = 30
FPS_UPDATE_INTERVAL = 30  # 每30帧更新一次FPS显示
MIN_MOVE_DISTANCE = 2  # 最小移动阈值

# 手势检测配置
HAND_DETECTION_CONFIDENCE = 0.8
MAX_HANDS = 1

# UI配置
UI_SCORE_POSITION = [50, 80]
UI_SCORE_SCALE = 3
UI_RESTART_POSITION = [50, SCREEN_HEIGHT - 50]
UI_FPS_POSITION = [SCREEN_WIDTH - 150, 50]
UI_HAND_STATUS_POSITION = [50, SCREEN_HEIGHT - 100]

# 游戏结束画面配置
GAME_OVER_POSITION = [SCREEN_WIDTH//2 - 200, SCREEN_HEIGHT//2]
GAME_OVER_SCALE = 5
FINAL_SCORE_POSITION = [SCREEN_WIDTH//2 - 200, SCREEN_HEIGHT//2 + 100]
FINAL_SCORE_SCALE = 3